CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;
CREATE EXTENSION IF NOT EXISTS postgis_topology;

CREATE TABLE IF NOT EXISTS health_outcomes
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year VARCHAR(4) NOT NULL,
    state_abbr VARCHAR(2) NOT NULL,
    state_desc VARCHAR(30) NOT NULL,
    county_name VARCHAR(30) NOT NULL,
    county_fips VARCHAR(5) NOT NULL,
    data_source VARCHAR(30) NOT NULL,
    category VARCHAR(30) NOT NULL,
    measure VARCHAR(100) NOT NULL,
    data_value_unit VARCHAR(30) NOT NULL,
    data_value_type VARCHAR(30) NOT NULL,
    data_value DOUBLE PRECISION NOT NULL,
    low_confidence_limit DOUBLE PRECISION NOT NULL,
    high_confidence_limit DOUBLE PRECISION NOT NULL,
    total_population INTEGER NOT NULL,
    total_adult_population INTEGER NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    census_tract_id VARCHAR(11) NOT NULL,
    category_id VARCHAR(30) NOT NULL,
    measure_id VARCHAR(30) NOT NULL,
    data_value_type_id VARCHAR(30) NOT NULL,
    short_question_text VARCHAR(100) NOT NULL
);