CREATE TABLE IF NOT EXISTS vehicles_available
(
    id                           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tract_name                   TEXT,
    total_households             VARCHAR(9),
    total_households_no_vehicle  VARCHAR(9),
    total_households_one_vehicle VARCHAR(9),
    tract_id                     VARCHAR(11) NOT NULL
);



CREATE TABLE IF NOT EXISTS internet_subscriptions
(
    id                                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tract_name                          TEXT,
    total_households                    VARCHAR(9),
    total_households_no_internet_access VARCHAR(9),
    tract_id                            VARCHAR(11) NOT NULL
);



CREATE TABLE IF NOT EXISTS poverty
(
    id                                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tract_name                           TEXT,
    total_population                     VARCHAR(9),
    total_population_below_poverty_level VARCHAR(9),
    tract_id                             VARCHAR(11) NOT NULL
);



CREATE TABLE IF NOT EXISTS health_insurance
(
    id                         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tract_name                 TEXT,
    total_population           VARCHAR(9),
    total_population_uninsured VARCHAR(9),
    tract_id                   VARCHAR(11) NOT NULL
);
