CREATE TABLE IF NOT EXISTS vehicles_available
(
    id                          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tract_name                  TEXT,
    total_households            VARCHAR(9),
    total_households_no_vehicle VARCHAR(9),
    tract_id                    VARCHAR(11) NOT NULL
);



CREATE TABLE IF NOT EXISTS internet_subscriptions
(
    id                                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tract_name                          TEXT,
    total_households                    VARCHAR(9),
    total_households_no_internet_access VARCHAR(9),
    tract_id                            VARCHAR(11) NOT NULL
);